export const GET_CONTENT = "GET_CONTENT";
export const GET_CONTENT_LOADING = "GET_CONTENT_LOADING";
export const GET_CONTENT_ERROR = "GET_CONTENT_ERROR";

export const POST_CONTACT = "POST_CONTACT";
export const POST_CONTACT_LOADING = "POST_CONTACT_LOADING ";
export const POST_CONTACT_ERROR = "POST_CONTACT_ERROR";
